image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

stages:
  - test

test:
  services:
    - selenium/standalone-chrome:latest

  script:
    - pytest --alluredir=reports/allure-report

  artifacts:
    paths:
      - /REPORTS/allure-report
      - /REPORTS/LOGS